### ISSUE TITLE
Wrong elevation calculation

### ISSUE THREAD

**Issue by Zumili** [kd2bd/predict#14]
Hello guys, I just figured out, that the elevation calculation does not work as expected.

My **predict.qth** looks like this
```
-----
 47.8375
 8.6994
 250
```

**TLE** file are created like this:
```
wget -qr https://www.celestrak.com/NORAD/elements/weather.txt -O $INSTALL_DIR/weather.txt
grep "NOAA 15" $INSTALL_DIR/weather.txt -A 2 >> $INSTALL_DIR/weather.tle
grep "NOAA 18" $INSTALL_DIR/weather.txt -A 2 >> $INSTALL_DIR/weather.tle
grep "NOAA 19" $INSTALL_DIR/weather.txt -A 2 >> $INSTALL_DIR/weather.tle
```

After calling for e.g.:
`/usr/bin/predict -t weather.tle -p "NOAA 19" 1599492107`

I get the following:

```
1599497281 Mon 07Sep20 16:48:01    0  130  132   27  345   3426  59700 *
1599497382 Mon 07Sep20 16:49:42    6  124  136   33  346   2814  59700 *
1599497483 Mon 07Sep20 16:51:23   14  115  140   38  348   2251  59700 *
1599497583 Mon 07Sep20 16:53:03   22   99  144   44  350   1798  59700 *
1599497678 Mon 07Sep20 16:54:38   29   75  148   50  353   1543  59700 *
1599497768 Mon 07Sep20 16:56:08   28   46  152   55  355   1550  59700 *
1599497858 Mon 07Sep20 16:57:38   22   23  156   60  358   1799  59700 *
1599497953 Mon 07Sep20 16:59:13   14    8  160   65    3   2232  59700 *
1599498053 Mon 07Sep20 17:00:53    7  359  164   70   10   2782  59700 *
1599498154 Mon 07Sep20 17:02:34    0  353  168   75   21   3393  59700 *
```
Showing me that the maximum elevation of this pass is **29°** at **16:54:38** but I know, from tools like **Gpredict**, that the satellites maximum elevation is **87°** at **16:54:07** so it is passing right above my head. The little time difference should be no issue, but the wrong elevation calculation is a big problem for scripts that use **predict** for automated satellite receiving.

I can verify this problem with other predictions of other satellites. It looks, that the elevation is often but not always too small. Tested it with version 2.2.3 and version 2.2.5.

It also looks, that this is only happening when the satellite passes  **east** of the ground station. That should be the cause, why I only get images where my ground station (Germany) is on the **right side** of the images (satellite passing west of ground station). I never got an automatic  image where my ground station  is on the left side (satellite passing right of ground station) of the image. And because I configured the script that it only receives images when the elevation is bigger than 30. I will not record passes right of my ground station due the wrong elevation prediction.

Can somebody somehow verify that the elevation calculation is wrong or is this a known problem?

Greetings Thomas

**Comment by pfranchini** [comment]
where do you live? is +8.6994 or -8.6994? Is negative for east of Greenwich.

**Comment by Zumili** [comment]
I live in south Germany, the **predict.qth** should be correct with a positive number for east.
I just edited my first text and have not expected, that somebody will ask so quick, sorry for that.

It seems, that the wrong elevation calculation only occurs, when the satellite passes "east" of the ground station!

**Comment by pfranchini** [comment]
Is definitely negative so, I made the same mistake. 
   *  Ground Station Location Editing Utility  *
   Station Longitude : -12.2237 [DegW]

the default is DegW, so for East is negative.

**Comment by Zumili** [comment]
You are absolutely right! That was the problem! I changed it 2 weeks ago and have got good images, even the AOS and LOS times seemed to be correct, so I was quite sure from that moment, that the Longitude is correct set. 
Thank you very much for the clarification.

**Comment by pfranchini** [comment]
no worries
